name: CD - Deploy to EC2
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            if [ ! -d "/home/ec2-user/car-cleaning-service" ]; then
              cd /home/ec2-user
              git clone https://github.com/devxtra-community/car-cleaning-service.git
            fi
            cd /home/ec2-user/car-cleaning-service
            git fetch origin main
            git reset --hard origin/main
            export HUSKY=0
            export NODE_OPTIONS="--max-old-space-size=2048"

            # Build frontend and copy to nginx folder
            cd apps/web
            npx pnpm install
            npx pnpm run build
            sudo rm -rf /var/www/carwash/*
            sudo cp -r dist/* /var/www/carwash/

            # Build backend
            cd /home/ec2-user/car-cleaning-service/backend
            npx pnpm install
            npx pnpm run build
            pm2 restart car-cleaning-api || pm2 start dist/index.js --name car-cleaning-api
            pm2 save